@startuml
title méthode prendreBouclier
actor Jeu
participant Labyrinthe

Jeu -> Labyrinthe: deplacerPerso(action)
activate Labyrinthe
deactivate Labyrinthe

Labyrinthe -> Joueur : getX()
Joueur --> Labyrinthe : x
Labyrinthe -> Joueur : getY()
Joueur --> Labyrinthe : y

Labyrinthe -> Joueur : prendreBouclier(x,y)
Joueur --> Labyrinthe : void
Labyrinthe --> Jeu: void
deactivate Labyrinthe
@enduml
